### ISSUE TITLE
sysrandom

### ISSUE THREAD

**Issue by sakuro** [rafaelsales/ulid#13]
This gem depends on [sysrandom](https://github.com/cryptosphere/sysrandom) gem, but it is archived already.

Because Ruby 2.5+ [tries to use /dev/urandom before openssl](https://bugs.ruby-lang.org/projects/ruby-trunk/repository/trunk/revisions/57384), we can rely on it and remove dependency to sysrandom if we drop support Ruby < 2.5. What do you think?

**Comment by suratpyari** [comment]
SecureRandom is available in ruby 1.9 and onwards.
