### ISSUE TITLE
Lexicographic Sort Order?

### ISSUE THREAD

**Issue by renenw** [rafaelsales/ulid#4]
Hello. I assumed that this meant that I could sort the ULID's - in other words, newer ID's should fall lexicographically after earlier ones:

> In mathematics, the lexicographic or lexicographical order (also known as lexical order, dictionary order, alphabetical order or lexicographic(al) product) is a generalization of the way the alphabetical order of words is based on the alphabetical order of their component letters.

So:

```
Loading development environment (Rails 5.0.0.rc2)
irb(main):001:0> ULID.generate
=> "7S2SYCSA109VJ4Z2ZVB4PBRCDV"
irb(main):002:0> ULID.generate
=> "6K4SYCSA10EVAK6F5E32R1K50C"
irb(main):003:0> ULID.generate
=> "6J6SYCSA10186DZ41ZBV57PZFV"
irb(main):004:0> ULID.generate
=> "Z98SYCSA1036VDH0ANC31A9YNZ"
irb(main):005:0> ULID.generate
=> "EMASYCSA10NEYETVH1DQPPMKJM"
irb(main):006:0> ULID.generate
=> "8CAVYCSA104HS6BH2VBMBMK4TK"
irb(main):007:0> ULID.generate
=> "EYBVYCSA1078FH66T8TZKYV9EX"
irb(main):008:0> ULID.generate
=> "PWDVYCSA108QKE6F8W36TTDJX8"
irb(main):009:0> ULID.generate
=> "X2FVYCSA1031REQ1M1Y00GH33P"
irb(main):010:0> ULID.generate
=> "XDGVYCSA1088A9DZFK7A042GPX"
irb(main):011:0> ULID.generate
=> "XRHVYCSA10KXJ73TGCBCYPDWR7"
irb(main):012:0> ULID.generate
=> "6VJVYCSA100JB4D804HDBNPMVD"
```

 You can see that those entries are not sortable (6VJVYCSA100JB4D804HDBNPMVD sorts before XRHVYCSA10KXJ73TGCBCYPDWR7, and if I'm wrong on that, then 8CAVYCSA104HS6BH2VBMBMK4TK is out of sequence).

Am I missing something?

renen.

**Comment by rafaelsales** [comment]
Fixed:

``` ruby
irb(main):012:0> a, b, c = 3.times.map { ULID.generate }
=> ["01ASDJN14PS2ES9TCN49JG14GR", "01ASDJN14PP1ZX1D9Z2TQY15P8", "01ASDJN14PEAH58HE23K00PJRR"]
irb(main):013:0> a > b
true
irb(main):014:0> b > c
true
```

Thanks for reporting
