### ISSUE TITLE
I think I broke ULID

### ISSUE THREAD

**Issue by catharinejm** [rafaelsales/ulid#7]
It has been brought to my attention that ULID has a (sort of) standard associated with it, originating in this javascript repo: https://github.com/alizain/ulid. I honestly thought you had invented it.... Whoops! So, my changes actually break compatibility with the javascript implementation and use an incorrect binary layout in the binary format.

I'm thinking it makes the most sense to roll back the changes and call it a new release... I don't think gems can be un-released, so that may be the only option.

**Comment by gottfrois** [comment]
any update on this?

**Comment by dcuddeback** [comment]
I submitted a PR that should fix this: https://github.com/rafaelsales/ulid/pull/10
