### ISSUE TITLE
It's not clear how to use ULID in Rails apps

### ISSUE THREAD

**Issue by vassilevsky** [rafaelsales/ulid#9]
How to replace UUIDs with ULIDs in a Rails app that uses UUIDs as primary keys (in PostgreSQL)?

**Comment by george** [comment]
The PG implementation of ULIDs appear to be a WIP: https://github.com/schinckel/ulid-postgres  And the last commit on the PG library was 7 Dec 2016 so I'm not sure if it's still being worked on.

**Comment by joelvh** [comment]
@vassilevsky you could set the ID with an `after_initialize` callback on the model or the `default_value` gem.
